config/routes.rb
Rails.application.routes.draw do

  root 'cafes#index'

  get '/cafes/login' => 'cafe_sessions#new'
  get '/cafes/profile' => 'cafes#show'
  post '/cafes/borough' => 'cafes#borough'
  post '/cafes/neighborhood' => 'cafes#neighborhood'
  post '/coffee_gifts/filter' => 'coffee_gifts#filter'

  resources :cafes, only: [:index, :show] do
    resources :coffee_gifts, only: [:new, :create]
  end

  resources :menu_items, only: [:destroy, :create, :update]
  resources :users, only: [:create]
  resources :coffee_gifts, only: [:show, :update]
  resources :transactions, only: [:new, :create]

  get '/login' => 'user_sessions#new'
  post '/users/sessions' => 'user_sessions#create'
  delete '/logout' => 'user_sessions#destroy'
  get '/profile' => 'users#show'
  get '/register' => 'users#new'
  get '/confirmation/:id' => 'coffee_gifts#confirm', as: "confirmation"

  get '/redemption_confirmation/:id' => 'coffee_gifts#confirm_redemption', as: "redemption_confirmation"

  post '/cafes/sessions' => 'cafe_sessions#create'
  delete '/cafes/logout' => 'cafe_sessions#destroy'

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
	belongs_to :cafe
	has_many :coffee_gifts

	validates_presence_of :name, :price
	validates :name, length: {maximum: 30}
  validates :price, :format => { :with => /\A\d{1,4}(\.\d{0,2})?\z/ }, :numericality => {:greater_than => 0.99}

  def combined_value
    "#{self.name} ($#{self.price})"
  end

end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :find_menu_item, :authenticate_cafe
  before_action :authorize_cafe, except: [:create]

  def create
    cafe = current_cafe
    menu_item = cafe.menu_items.build(menu_item_params)
    menu_item.save
    redirect_to cafes_profile_path
  end

  def update
    @cafe = @menu_item.cafe
    @menu_item.update_attributes(menu_item_params)
    redirect_to cafes_profile_path
  end

  def destroy
    @cafe = @menu_item.cafe
    @menu_item.destroy
    redirect_to cafes_profile_path
  end

  private

  def menu_item_params
    params.require(:menu_item).permit(:name, :price)
  end

  def find_menu_item
    @menu_item = MenuItem.find_by_slug(params[:id])
  end

  def authenticate_cafe
    redirect_to root_path unless current_cafe
  end

  def authorize_cafe
    redirect_to root_path unless current_cafe.owns_item?(@menu_item)
  end
end

app/views/menu_items/_delete.html.erb
<%= form_for menu_item, url: menu_item_path(menu_item) do |f| %>
<%= hidden_field_tag "_method", "delete" %>
<%= f.submit "Delete item", :class=>"button tiny round alert" %>
<% end %>

app/views/menu_items/_display_item.html.erb
<%= menu_item.name %>: $<%=format_price(menu_item.price) %>

app/views/menu_items/_edit.html.erb
<%= form_for menu_item, url: menu_item_path(menu_item) do |f| %>
  <%= hidden_field_tag "_method", "put" %>
  <%= f.label :name %>
  <%= f.text_field :name, value: menu_item.name %>
  <%= @menu_item.errors[:name].first %>

  <%= f.label :price %>
  <%= f.text_field :price, value: format_price(menu_item.price) %>
  <%= @menu_item.errors[:price].first %>

  <%= f.submit "Update item", :class=>"button tiny round" %>
<% end %>

app/views/menu_items/_menu_item.html.erb
<li>
  <ul>
   <h4><%= menu_item.name %>: $<%= format_price(menu_item.price) %></h4>
   <li>
    <%= render partial:"menu_items/delete", locals: {menu_item: menu_item, cafe: @cafe} %>
  </li>
  <li>
    <%= render partial:"menu_items/edit", locals: {menu_item: menu_item, cafe: @cafe} %>
  </li>
</ul>
</li>

app/views/menu_items/_new.html.erb
<%= form_for @menu_item, url: menu_items_path(@menu_item) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, value: @menu_item.name %>
  <%= @menu_item.errors[:name].first %>

  <%= f.label :price %>
  <%= f.text_field :price, value: @menu_item.price %>
  <%= @menu_item.errors[:price].first %>

  <%= f.submit "Add new item", :class=>"button tiny round" %>
<% end %>