config/routes.rb
Rails.application.routes.draw do

  root 'cafes#index'

  get '/cafes/login' => 'cafe_sessions#new'
  get '/cafes/profile' => 'cafes#show'
  post '/cafes/borough' => 'cafes#borough'
  post '/cafes/neighborhood' => 'cafes#neighborhood'
  post '/coffee_gifts/filter' => 'coffee_gifts#filter'

  resources :cafes, only: [:index, :show] do
    resources :coffee_gifts, only: [:new, :create]
  end

  resources :menu_items, only: [:destroy, :create, :update]
  resources :users, only: [:create]
  resources :coffee_gifts, only: [:show, :update]
  resources :transactions, only: [:new, :create]

  get '/login' => 'user_sessions#new'
  post '/users/sessions' => 'user_sessions#create'
  delete '/logout' => 'user_sessions#destroy'
  get '/profile' => 'users#show'
  get '/register' => 'users#new'
  get '/confirmation/:id' => 'coffee_gifts#confirm', as: "confirmation"

  get '/redemption_confirmation/:id' => 'coffee_gifts#confirm_redemption', as: "redemption_confirmation"

  post '/cafes/sessions' => 'cafe_sessions#create'
  delete '/cafes/logout' => 'cafe_sessions#destroy'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render 'index'
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_cafe_login.html.erb
 <div id="cafe-login">

  <header class="popupHeader">
    <h3 class="header_title">Cafe Log In</h3>
    <div class="modal_close"><%= image_tag("grey-close.png") %></div>
  </header>

  <div id="cafe-login-errors" class="popupErrors">
    <% if flash[:cafe_error] %>
        <p><%= flash[:cafe_error] %></p>
    <% end %>
  </div>  

  <section class="popupBody">
    <%= form_for :cafe_session, url: cafes_sessions_path do |f| %>
    <%= f.text_field :email, placeholder: "Email", label: false%>
    <%= f.password_field :password, placeholder: "Password", label: false%>
    <%= f.submit "Login", class: "button tiny" %>
    <% end %>
    <label id="login-as-user" class="secondary label radius">Log in as a user</label>
  </section>

</div>

app/views/welcome/_login.html.erb
<div id="login-modal" class="popupContainer">

  <div id="user-login">

    <header class="popupHeader">
      <h3 class="header_title">Log In</h3>
      <div class="modal_close"><%= image_tag("grey-close.png") %></div>
    </header>

    <div id="user-login-errors" class="popupErrors">
    <% if flash[:login_error] %>
        <p><%= flash[:login_error] %></p>
    <% end %>
    </div>  

    <section class="popupBody">
     <%= form_for(:user_session, url: users_sessions_path) do |f| %>
     <%= f.text_field :email, placeholder: "Email" , label: false%>
     <%= f.password_field :password, placeholder: "Password", label: false%>
     <%= f.submit "Log in", class: "button tiny" %>
     <% end %>
     <label id="login-as-cafe" class="secondary label radius">Log in as a cafe</label>
   </section>
 </div>

 <%= render "welcome/cafe_login" %>

</div>

app/views/welcome/_register.html.erb
<div id="register-modal" class="popupContainer">
  <header class="popupHeader">

    <h3 class="header_title">Register</h3>
    <div class="modal_close"><%= image_tag("grey-close.png") %></div>
  </header>

  <div id="registration-errors" class="popupErrors">
    <% if flash[:reg_error] %>
      <% flash[:reg_error].each do |error| %>
        <p><%=error%></p>
      <% end %>
    <% end %>
  </div>  

  <section class="popupBody user-register">
    <%= form_for :user, url: users_path do |f| %>
    <%= f.text_field :first_name, placeholder: "First Name", label: false%>
    <%= f.text_field :last_name, placeholder: "Last Name", label: false%>
    <%= f.email_field :email, placeholder: "Email", label: false%>
    <%= f.telephone_field :phone, placeholder: "Phone", maxlength: "10", label: false %>
    <%= f.password_field :password, placeholder: "Password", label: false%>
    <%= f.submit :Register, :class=>"button tiny" %>
  <% end %>

    </section>
</div>