config/routes.rb
Rails.application.routes.draw do

  root 'cafes#index'

  get '/cafes/login' => 'cafe_sessions#new'
  get '/cafes/profile' => 'cafes#show'
  post '/cafes/borough' => 'cafes#borough'
  post '/cafes/neighborhood' => 'cafes#neighborhood'
  post '/coffee_gifts/filter' => 'coffee_gifts#filter'

  resources :cafes, only: [:index, :show] do
    resources :coffee_gifts, only: [:new, :create]
  end

  resources :menu_items, only: [:destroy, :create, :update]
  resources :users, only: [:create]
  resources :coffee_gifts, only: [:show, :update]
  resources :transactions, only: [:new, :create]

  get '/login' => 'user_sessions#new'
  post '/users/sessions' => 'user_sessions#create'
  delete '/logout' => 'user_sessions#destroy'
  get '/profile' => 'users#show'
  get '/register' => 'users#new'
  get '/confirmation/:id' => 'coffee_gifts#confirm', as: "confirmation"

  get '/redemption_confirmation/:id' => 'coffee_gifts#confirm_redemption', as: "redemption_confirmation"

  post '/cafes/sessions' => 'cafe_sessions#create'
  delete '/cafes/logout' => 'cafe_sessions#destroy'

end

app/models/coffee_gift.rb
class CoffeeGift < ActiveRecord::Base
	belongs_to :menu_item
	belongs_to :receiver, class_name: :User
	belongs_to :giver, class_name: :User

	delegate :name, to: :menu_item
	delegate :cafe, to: :menu_item
  delegate :price, to: :menu_item
 
  before_save :generate_slug, :generate_redemption_code

  validates_presence_of :menu_item
  validates_presence_of :phone, unless: Proc.new { |gift| gift.charitable }

  def assign_phone(params)
    self.menu_item = MenuItem.find_by(id: params[:menu_item])
    self.receiver = User.find_by(id: params[:receiver]) || User.find_by(phone: params[:phone])
    self.phone = self.receiver.phone if self.phone.blank? && self.receiver
  end

  def to_param
    "#{self.id}-#{slug}"
  end

  private

  def generate_redemption_code
    self.redemption_code = rand(36**8).to_s(36)
  end

  def generate_slug
    self.slug = self.name.parameterize
  end

end

app/controllers/coffee_gifts_controller.rb
class CoffeeGiftsController < ApplicationController

	before_action :authenticate_user, except: [:update, :filter, :confirm_redemption]
	before_action :find_coffee_gift, except: [:new, :create, :filter]
	before_action :authorize_user, only: [:show]
	before_action :find_cafe, except: [:new, :create, :update]

	def new
		if request.xhr?
			flash[:auth_error] = "Please login to send coffee." unless current_user
			@cafe = Cafe.find_by(id: params[:cafe_id])
		else
			@cafe = Cafe.find_by(slug: params[:cafe_id])
		end
		@menu_items = @cafe.menu_items
		@receivers = User.all
		@coffee_gift = CoffeeGift.new
		render :new, layout: !request.xhr?
	end

	def create
		cafe = Cafe.find_by(slug: params[:cafe_id])
		coffee_gift = current_user.given_coffees.build(coffee_gift_params)
		coffee_gift.assign_phone(params[:coffee_gift])
		if coffee_gift.save
			session[:tmp_id] = nil
			session[:tmp_id] = coffee_gift.id
			session[:tmp_price] = coffee_gift.price
			redirect_to new_transaction_path
		else
			coffee_gift.destroy
			flash[:error] = coffee_gift.errors.full_messages
			redirect_to cafe_path(cafe)
		end
	end

	def update
		if @coffee_gift.update_attributes(redeemed: true)
			flash[:notice] = "Coffee Redeemed!"
			TwilioTextSender.send!(@coffee_gift)
			redirect_to redemption_confirmation_path
		else
			flash[:error] = ["Unable to redeem voucher"]
			redirect_to cafes_profile_path
		end
	end

	def redemption_confirmation
	end

	def show
	end

	def confirm_redemption
	end

	def confirm	
	end

	private

	def find_coffee_gift
		@coffee_gift = CoffeeGift.find_by(id: params[:id].split("-").first)
	end

	def find_cafe
		@cafe = @coffee_gift.cafe
	end	

	def authorize_user
		find_coffee_gift
		redirect_to root_path unless current_user.sent_or_received_coffee?(@coffee_gift)
	end

	def authenticate_user
		unless current_user || request.xhr?
			flash[:error] = ["Please login to send coffee."]
			redirect_to root_path
		end
	end

	def coffee_gift_params
		params.require(:coffee_gift).permit(:message, :phone, :charitable)
	end

end

app/views/coffee_gifts/_coffee_gift.html.erb
<ul class="no-bullet">
<% coffee_gifts.each do |gift| %>
  <% if gift.redeemed %>
    <li class="coffee_padding">
    <%= link_to "#{gift.cafe.name} (#{gift.name})", coffee_gift_path(gift), class: "coffee-gift redeemed" %>
    </li>
  <% else %>
    <li class="coffee_padding">
    <%= link_to "#{gift.cafe.name} (#{gift.name})", coffee_gift_path(gift), class: "coffee-gift unredeemed" %>
    </li>
  <% end %>
  <br>
<%end%>
</ul>

app/views/coffee_gifts/_error.html.erb
Please log in to send coffee

app/views/coffee_gifts/confirm.html.erb
<div class="row low_content add_content_padding">
  <% if flash[:error] %>

    <h1><%=flash[:error]%></h1>
    <hr>

  <% else  %>

    <% if flash[:notice] %>
     <h1><%=flash[:notice]%></h1>
     <hr>
    <% end %>

    <div class="success-panel text-center">
      <p>Coffee has been sent </p>
    </div>

  <% if @coffee_gift.charitable %>
    <h4 class="text-center">
    You rock! Thank you for making someone's day a little brighter.
    <h4>
  <% elsif @coffee_gift.receiver %>

    <% if flash[:twilio_error] %>
      <div class="fail-panel-yellow text-center">
        <p><%=flash[:twilio_error]%></p>
      </div>
    <% else %>
      <h4 class="text-center">
      We'll send an SMS to <span class="bold"><%=@coffee_gift.receiver.full_name%></span>
      <h4>
    <% end %>

    <h4 class="text-center">
    They can pick up their <span class="bold"><%=@coffee_gift.name%></span> at <span class="bold"><%=@cafe.name%></span>.
     <h4>
  <% else %>
      <% if flash[:twilio_error] %>
        <div class="fail-panel-yellow text-center">
          <p><%=flash[:twilio_error]%></p>
        </div>
      <% else %>
        <h4 class="text-center">
        We'll send an SMS to <span class="bold"><%=format_phone(@coffee_gift.phone)%></span>
        <h4>
      <% end %>

      <h4 class="text-center">
      Your friend can pick up their <span class="bold"><%=@coffee_gift.name%></span> at <span class="bold"><%=@cafe.name%></span>.
       <h4>
  <% end %>

    <hr>
    <%= link_to "Back to Profile", profile_path, :class =>"button expanded small-8 small-offset-2 medium-4 medium-offset-4 large-2 large-offset-5 columns text-centered" %>
    </div>

<%end%>
</div>

app/views/coffee_gifts/confirm_redemption.html.erb
<div class="row low_content add_content_padding">
  <div class= "small-12 column">
<% if flash[:error] %>
  <h1><%=flash[:error]%></h1>
  <hr>
<% else  %>
  <% if flash[:notice] %>
   <h1><%=flash[:notice]%></h1>
   <hr>
  <% end %>
  <div class="success-panel text-center">
    <p>Redemption Confirmed</p>
  </div>
  <% if @coffee_gift.charitable %>
    <h4 class="text-center">
    Please make a cup of "<%=@coffee_gift.name%>" to brighten up this person's day. Thank You!
    <h4>
  <% else %>
    <h4 class="text-center">
    Please make a cup of <%=@coffee_gift.name%> and brighten up <span class="bold"><%=@coffee_gift.receiver.full_name%>'s</span> day!
    <h4>
  <% end %>
<% end %>
<hr>
<%= link_to "Back to Profile", @cafe, :class =>"button expanded small-8 small-offset-2 medium-4 medium-offset-4 large-2 large-offset-5 columns text-centered" %>
  </div>
</div>

app/views/coffee_gifts/new.html.erb
<div class="coffee-gift-form">
    <% if flash[:auth_error] %>
        <%=flash[:auth_error]%>
    <% else %>
        <div id="new_coffee" >
          <%= form_for @coffee_gift, url: cafe_coffee_gifts_path(@cafe) do |f| %>

            <div class="spacer">
            <%= f.collection_select(:receiver, @receivers, :id, :combined_value, include_blank: true, label:false)  %>
            <%= @coffee_gift.errors[:reciever].first %>
            </div>

            <%= f.text_field :phone, placeholder: "Option 2: Enter a phone number", maxlength: "10", label: false %>
            <%= @coffee_gift.errors[:phone].first %>

            <%= f.check_box :charitable, label: "Option 3: Buy coffee for a stranger" %>

            <%= f.text_area :message, size: "30x6", placeholder: "Include a personal note!", label: false  %>

            <%= f.hidden_field :menu_item, :value => "$menu_item_id" %>
            <%= f.submit "Send coffee", :class=>"button expand send-coffee" %>
          <% end %>
        </div>
    <% end %>
</div>

app/views/coffee_gifts/redemption_confirmation.html.erb
<div class="row">
  <div class= "small-12 column">
<% if flash[:error] %>
  <h1><%=flash[:error]%></h1>
  <hr>
<% else  %>
  <% if flash[:notice] %>
   <h1><%=flash[:notice]%></h1>
   <hr>
  <% end %>
  <div class="success-panel text-center">
    <p>Redemption Confirmed</p>
  </div>
  <% if @coffee_gift.charitable %>
    <h4 class="text-center">
    Please make a cup of <%=@coffee_gift.name%> to earn some extra karma!
    <h4>
  <% else %>
    <h4 class="text-center">
    Please make a cup of <%=@coffee_gift.name%> and brighten up <span class="bold"><%=@coffee_gift.receiver.full_name%>'s</span> day!
    <h4>
  <% end %>
<% end %>
  </div>
</div>
<div class="row">
  <div class= "small-2 columns small-centered">
    <%= link_to "Go Back", @cafe, :class =>"button" %>
  </div>
</div>

app/views/coffee_gifts/show.html.erb
<% if current_user.received_coffee?(@coffee_gift) %>

  <% if @coffee_gift.redeemed %>
  <div class="row low_content">
      <div class="small-12 columns">
        <ul class="pricing-table add_margin">
          <li class="price"> This gift has been redeemed!</li>
        </ul>
      </div>
  </div>
  <% else %>
  <div class="row low_content">
      <div class="small-12 columns ">
      <ul class="pricing-table add_margin">
        <li class="price"> Yay! You received a <span class="bold"><%=@coffee_gift.name%></span> from <span class="bold"><%=@coffee_gift.giver.first_name%> <%=@coffee_gift.giver.last_name%></span></li>
        <li class="price">Your voucher code is:</li>
        <li class="price"><kbd><%=@coffee_gift.redemption_code%></kbd></li>
        <li class="price"> You can pick it up at <span class="bold"><%=@cafe.name%></span>
          <hr>
            <div style="height:350px;width:100%" id="map"></div>
                  <input id="address" type="hidden" value="<%=@cafe.address%>">
        </li>
        <li class="bullet-item"><%=@cafe.address %></li>
      </ul>
    </div>
  </div>
  <% end %>

<% else %>

  <div class="row low_content">
      <div class="small-12 columns">
      <ul class="pricing-table add_margin">
        <li class="price"> You sent a <span class="bold"><%=@coffee_gift.name%></span> to <span class="bold">
          <% if @coffee_gift.receiver %>
            <%=@coffee_gift.receiver.first_name%> <%=@coffee_gift.receiver.last_name%>
          <% else %>
            <%=@coffee_gift.phone%>
          <% end %>
          </span> on <span class="bold"><%=@coffee_gift.created_at.strftime("%B %d, %Y")%></span></li>
      </ul>
    </div>
  </div>

<% end %>