config/routes.rb
Rails.application.routes.draw do

  root 'cafes#index'

  get '/cafes/login' => 'cafe_sessions#new'
  get '/cafes/profile' => 'cafes#show'
  post '/cafes/borough' => 'cafes#borough'
  post '/cafes/neighborhood' => 'cafes#neighborhood'
  post '/coffee_gifts/filter' => 'coffee_gifts#filter'

  resources :cafes, only: [:index, :show] do
    resources :coffee_gifts, only: [:new, :create]
  end

  resources :menu_items, only: [:destroy, :create, :update]
  resources :users, only: [:create]
  resources :coffee_gifts, only: [:show, :update]
  resources :transactions, only: [:new, :create]

  get '/login' => 'user_sessions#new'
  post '/users/sessions' => 'user_sessions#create'
  delete '/logout' => 'user_sessions#destroy'
  get '/profile' => 'users#show'
  get '/register' => 'users#new'
  get '/confirmation/:id' => 'coffee_gifts#confirm', as: "confirmation"

  get '/redemption_confirmation/:id' => 'coffee_gifts#confirm_redemption', as: "redemption_confirmation"

  post '/cafes/sessions' => 'cafe_sessions#create'
  delete '/cafes/logout' => 'cafe_sessions#destroy'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include UserSessionsHelper
  include CafeSessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-6 columns">
        <p>© Copyright no one at all. Go to town.</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="#">Link 1</a></li>
          <li><a href="#">Link 2</a></li>
          <li><a href="#">Link 3</a></li>
          <li><a href="#">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/application/_header.html.erb
<div class="row">
  <div class="large-12 columns">


    <nav class="top-bar" data-topbar>
      <ul class="title-area">

        <li class="name">
          <h1>
            <a href="#">
              CoffeeMates
            </a>
          </h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <ul class="left">
          <% if user_logged_in? %>
            <li><%= link_to "Profile", profile_path %></li>
            <li><%= link_to "Log Out", logout_path, method: :delete %></li>
          <% elsif cafe_logged_in? %>
            <li><%= link_to "Profile", cafes_profile_path %></li>
            <li><%= link_to "Log Out", cafes_logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up As User", register_path, class: "button" %></li>
            <li><%= link_to "Log In As User", login_path, class: "button" %></li>
            <li><%= link_to "Log In As Cafe", cafes_login_path, class: "button" %></li>
          <% end %>
        </ul>

        <ul class="right">
          <li class="search">
            <form>
              <input type="search">
            </form>
          </li>

          <li class="has-button">
            <a class="small button" href="#">Search</a>
          </li>
        </ul>
      </section>
    </nav>



  </div>
</div>